---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=reciprocity.conf.j2 dest=/etc/init/reciprocity.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=reciprocity state=restarted
