---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - postgresql-client
    - libpq-dev
    - python-pip
    - python-psycopg2
    - git
    - libjpeg-dev
    - libjpeg8-dev

- name: Clone Django Repository
  git: repo=https://github.com/TeamReciprocity/reciprocity.git dest={{ django_home }} force=yes version={{gh_version}}

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ django_home }}/requirements.txt"

- name: Change Media Ownership
  sudo: yes
  file: path={{django_home}}/reciprocity/media owner=www-data recurse=yes state=directory

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"

- name: Get DB Password
  include_vars: secrets.yml


- name: Set DB URL
  set_fact:
    db_url: "{{ db_host.ec2_engine }}://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

- name: Make Migrations
  environment:
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}/reciprocity"
    settings: reciprocity.production
    command: makemigrations

- name: Run Migrations
  environment:
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}/reciprocity"
    settings: reciprocity.production
    command: migrate

- name: Collect Static Files
  environment:
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}/reciprocity"
    settings: reciprocity.production
    command: collectstatic

- name: Use Fixture to Populate Database
  environment:
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}/reciprocity"
    settings: reciprocity.production
    fixtures: users.json
    command: loaddata

- name: Use Recipe Fixture to Populate Database
  sudo: yes
  environment:
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}/reciprocity"
    settings: reciprocity.production
    fixtures: recipes.json
    command: loaddata

- name: Use ingredients Fixture to Populate Database
  sudo: yes
  environment:
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}/reciprocity"
    settings: reciprocity.production
    fixtures: ingredients.json
    command: loaddata

- name: Use Relationship Fixture to Populate Database
  sudo: yes
  environment:
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}/reciprocity"
    settings: reciprocity.production
    fixtures: recipeingredientrelationship.json
    command: loaddata
